name: Main CI

on:
  push:
    branches:
      - main

jobs:
  test-java:
    name: Test Java Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run build and tests
        run: chmod +x ./gradlew; ./gradlew clean build
        working-directory: ./java-server

  test-and-publish-python-to-testpypi:
    name: Test and Publish Python to TestPyPI
    runs-on: ubuntu-latest
    needs: test-java # Javaのテストが成功したら実行
    permissions:
      id-token: write # TestPyPIへの信頼された公開に必要
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies and build package
        working-directory: ./python-client
        run: |
          pip install --system .[dev] # dev依存関係もインストール
          pytest # テスト実行
          python -m build --all-packages

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/
          skip-existing: true
          packages-dir: python-client/dist
          verbose: true