name: Release

on:
  release:
    types: [created]

jobs:
  build-java-fat-jar:
    name: Build Java Fat JAR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Fat JAR with shadowJar
        run: chmod +x ./gradlew; ./gradlew clean build shadowJar
        working-directory: ./java-server

      - name: Upload Fat JAR to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./java-server/build/libs/java-server-*-all.jar
          asset_name: Sota-gRPC-Server_${{ github.event.release.tag_name  }}.jar
          asset_content_type: application/java-archive

  build-python-wheel:
    name: Build Python Wheel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Build packages
        working-directory: ./python-client
        run: |
          pip cache purge
          pip install .
          python -m build --all-packages

      - name: Upload Python wheel to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./python-client/dist/*.whl
          asset_name: sotagrpc-${{  github.event.release.tag_name#v  }}-py3-none-any.whl # 適宜バージョンを修正
          asset_content_type: application/wheel

  publish-to-pypi:
    name: Publish Python to PyPI
    runs-on: ubuntu-latest
    needs: [build-java-fat-jar, build-python-wheel]
    if: github.event.release.prerelease == false # プレリリースでない場合のみ実行
    permissions:
      id-token: write # PyPIへの信頼された公開に必要
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build packages
        working-directory: ./python-client
        run: |
          pip cache purge
          pip install .
          python -m build --all-packages

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1